### PR TITLE
Player teams get added when we matchmake baby

### PR DESCRIPTION
**Pull request by Kevin-Burgos-9**

### CODE REVIEW

**Comment by julianramos1** [comment]
Se ve bien

**Review by julianramos1 — APPROVED** [review]
Se ve bien

**Review by fmaclang — COMMENTED** [review]
i trust this

**Comment by julianramos1** [comment]
JAJAJAJAJAJA

**Review by fmaclang — APPROVED** [review]
i trust this again 2.0

**Comment by julianramos1** [comment]
So we merge?

**Comment by Kevin-Burgos-9** [comment]
Can one of you just merge it?

**Pull request merged**
